<?php
/**
 * @file
 * Provides the ability to embed documents from Scribd.
 *
 * This module provides an input filter to add a document (from Scribd) anywhere
 * input filters are accepted. You have the option of replacing the filter tag
 * with a link to the scribd or embedding the scribd itself.
 */

/**
 * Implementation of hook_filter_info().
 */
function scribd_filter_filter_info() {
  $filters['scribd_filter'] = array(
    'title' => t('Scribd documents filter'),
    'description' => t('Substitutes [scribd id=xx key=yy] tags with the scribd document located at http://scribd.com/doc/xx.'),
    'process callback'  => 'scribd_filter_scribd_filter_process',
    'default settings' => array(
      'scribd_filter_display_method' => 'embed',
    ),
    'settings callback' => 'scribd_filter_scribd_filter_settings',
    'tips callback' => 'scribd_filter_filter_tips',
    'cache' => TRUE,
  );
  return $filters;
}

/**
 * Process callback for hook_filter_info().
 */
function scribd_filter_scribd_filter_process($text, $filter, $format) {
  $display = $filter->settings['scribd_filter_display_method'];
  $callback = '_scribd_display_' . $display;
  return preg_replace_callback('@\[scribd id=(\d+) key=(.*)\]@', $callback, $text);
}

/**
 * Settings callback for scribd_filter.
 */
function scribd_filter_scribd_filter_settings($form, $form_state, $filter, $format, $defaults) {
  $settings['scribd_filter_display_method'] = array(
    '#title' => t('Scribd display method'),
    '#type' => 'select',
    '#options' => array(
      'embed' => t('Embed'),
      'link' => t('Link'),
    ),
    '#default_value' => isset($filter->settings['scribd_filter_display_method']) ? $filter->settings['scribd_filter_display_method'] : $defaults['scribd_filter_display_method'],
  );
  return $settings;
}

/**
 * Implements hook_filter_tips().
 */
function scribd_filter_filter_tips($filter, $format, $long = FALSE) {
  $display = $filter->settings['scribd_filter_display_method'];
  $action = $display == 'embed' ? t('embed the scribd document') : t('create a link to the scribd document');
  return t('Use [scribd id=xx key=yy] where xx is you scribd document_id, yy is your scribd document access_key to %action.', array('%action' => $action));
}

/**
 * Display a Scribd.com file via iPaper by replacing the text.
 */
function _scribd_display_embed($matches) {
  $data['scribd_doc_id'] = $matches[1];
  $data['scribd_access_key'] = $matches[2];

  $output = array(
    '<script type="text/javascript" src="http://www.scribd.com/javascripts/view.js"></script>',
    '<div id="embedded_flash" class="collapsible collapsed"></div>',
    '<script type="text/javascript">',
    'var scribd_doc = scribd.Document.getDoc("' . check_plain($data['scribd_doc_id']) . '", "' . check_plain($data['scribd_access_key']) . '");',
    'scribd_doc.addParam("jsapi_version", 1);',
  );
  $output[] = 'scribd_doc.write("embedded_flash");';
  $output[] = '</script>';

  return implode("\n", $output);
}

/**
 * Replace the text with a link.
 */
function _scribd_display_link($matches) {
  $data['scribd_doc_id'] = $matches[1];
  $data['scribd_access_key'] = $matches[2];
  $scribd_url = 'http://www.scribd.com/full/' . check_plain($data['scribd_doc_id']) . '?access_key=' . check_plain($data['scribd_access_key']);
  return l($scribd_url, $scribd_url);
}
